- name: epelリポジトリ
  command: rpm -Uvh --replacepkgs https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm

- name: webtaticリポジトリ
  command: rpm -Uvh --replacepkgs https://mirror.webtatic.com/yum/el6/latest.rpm

- name: IUS (CentOS)リポジトリ
  yum: name=http://dl.iuscommunity.org/pub/ius/stable/CentOS/{{ ansible_distribution_major_version }}/{{ ansible_userspace_architecture }}/ius-release-1.0-13.ius.centos{{ ansible_distribution_major_version }}.noarch.rpm
  when: ansible_distribution == "CentOS"

- name: nginxリポジトリ
  command: rpm -Uivh --replacepkgs http://nginx.org/packages/centos/6/noarch/RPMS/nginx-release-centos-6-0.el6.ngx.noarch.rpm

- name: mysqlリポジトリ
  yum:
    name: http://dev.mysql.com/get/mysql57-community-release-el6-7.noarch.rpm
    state: present

- name: libselinuxをインストール
  yum: name=libselinux-python state=present

- name: selinux無効化
  selinux: state=disabled
  ignore_errors: true

#- name: firewallをストップする
#  service: name=firewalld enabled=true state=stopped
#  ignore_errors: true

#- name: development toolsをインストール
#  yum: name="@Development tools" state=present

- name: wgetをインストール
  yum: name=wget state=present

- name: 新しいバージョンのgitを試しに入れてみる 
  yum: name=git2u state=latest
  register: result
  ignore_errors: true

- name: 古いgitを削除
  yum: name=git state=absent
  when: result|failed

- name: 改めて新しいgitをインストール
  yum: name=git2u state=latest
  when: result|failed 

